Repository yumyum-web/imaginary-seychelles-bank-system, pull requests merged in 2024-10, with the labels that each got.

#35 34 fix pre commit linting configs
  SQL/package.json
  client/components.json
  client/eslint.config.js
  client/package.json
  client/postcss.config.js
  client/src/App.css
  client/src/components/custom/button.tsx
  client/src/components/ui/button.tsx
  client/src/components/ui/form.tsx
  client/src/components/ui/input.tsx
  client/src/components/ui/label.tsx
  client/src/lib/utils.ts
  client/src/main.tsx
  client/tailwind.config.js
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  server/eslint.config.js
  server/package.json
Labels: bug

#37 Refactor server for Typescript support
  pnpm-lock.yaml
  server/eslint.config.js
  server/package.json
  server/src/api/v1/api-doc.ts
  server/src/app.ts
  server/src/config.ts
  server/src/server.ts
  server/src/utils.ts
  server/tsconfig.json
Labels: backend

#40 38 implement auth endpoints and handlers
  pnpm-lock.yaml
  server/package.json
  server/src/api/config.ts
  server/src/api/v1/api-doc.ts
  server/src/api/v1/errors.ts
  server/src/api/v1/handlers/auth/login.ts
  server/src/api/v1/handlers/methodNotAllowed.ts
  server/src/api/v1/handlers/notFound.ts
  server/src/api/v1/handlers/notImplemented.ts
  server/src/api/v1/handlers/postResponseHandler.ts
  server/src/api/v1/handlers/unauthorizedHandler.ts
  server/src/api/v1/handlers/validationFail.ts
  server/src/api/v1/helpers/accessHierarchy.ts
  server/src/api/v1/helpers/db.ts
  server/src/api/v1/helpers/jwt.ts
  server/src/api/v1/models/User.ts
  server/src/api/v1/securityHandlers/jwtHandler.ts
  server/src/app.ts
  server/src/config.ts
  server/src/utils.ts
Labels: backend

#44 Add employee branch id to the login response
  server/src/api/v1/api-doc.ts
  server/src/api/v1/handlers/auth/login.ts
  server/src/api/v1/models/User.ts
Labels: backend

#48 Fix isLevelSufficientForLevel and jwtHandler algorithms
  server/src/api/v1/helpers/accessHierarchy.ts
  server/src/api/v1/securityHandlers/jwtHandler.ts
Labels: bug, backend

#45 Implemented the loan handlers
  SQL/loanprocedures.sql
  server/src/api/v1/api-doc.ts
  server/src/api/v1/handlers/loan/list.ts
  server/src/api/v1/handlers/loan/request/create.ts
  server/src/api/v1/handlers/loan/request/list.ts
  server/src/api/v1/handlers/loan/request/process.ts
  server/src/api/v1/handlers/loan/selfapply.ts
  server/src/app.ts
Labels: backend

#50 Profile of user, employee and oraganization updated
  server/src/api/v1/api-doc.ts
  server/src/api/v1/handlers/profile/employee.ts
  server/src/api/v1/handlers/profile/organization.ts
  server/src/api/v1/handlers/profile/user.ts
  server/src/app.ts
Labels: backend

#58 Implement functional endpoints
  SQL/Create_Savings_Checking_Fixed.sql
  SQL/bankschema.sql
  SQL/branchreports.sql
  SQL/customerProcedures.sql
  SQL/depositWithdrawalPeocedures.sql
  SQL/employeeProcedures.sql
  server/src/api/v1/api-doc.ts
  server/src/api/v1/handlers/account/checking/create.ts
  server/src/api/v1/handlers/account/checking/list.ts
  server/src/api/v1/handlers/account/deposit.ts
  server/src/api/v1/handlers/account/savings/create.ts
  server/src/api/v1/handlers/account/savings/list.ts
  server/src/api/v1/handlers/account/savings/plans.ts
  server/src/api/v1/handlers/account/transfer.ts
  server/src/api/v1/handlers/account/transferHistory.ts
  server/src/api/v1/handlers/account/withdraw.ts
  server/src/api/v1/handlers/fixedDeposit/create.ts
  server/src/api/v1/handlers/fixedDeposit/list.ts
  server/src/api/v1/handlers/fixedDeposit/plans.ts
  server/src/api/v1/handlers/report/branchWiseLateLoanInstallments.ts
  server/src/api/v1/handlers/report/branchWiseTotalTransactions.ts
  server/src/app.ts
Labels: backend

#59 Switch to query parameters for get endpoints
  server/src/api/v1/api-doc.ts
  server/src/api/v1/handlers/account/checking/list.ts
  server/src/api/v1/handlers/account/savings/list.ts
  server/src/api/v1/handlers/account/transferHistory.ts
  server/src/api/v1/handlers/fixedDeposit/list.ts
Labels: backend

#62 Added backend logic
  SQL/branchreports.sql
  SQL/package.json
  SQL/procedures.sql
  client/src/api/accounts.ts
  client/src/api/create.ts
  client/src/api/loans.ts
  client/src/api/plans.ts
  client/src/api/reports.ts
  client/src/api/types.ts
  client/src/components/forms/signIn.tsx
  client/src/pages/employee/createCheckingAccount.tsx
  client/src/pages/employee/createFixedDesposit.tsx
  client/src/pages/employee/createLoanRequest.tsx
  client/src/pages/employee/createSavingsAccount.tsx
  client/src/pages/manager/lateLoanInstallments.tsx
  client/src/pages/manager/loanRequests.tsx
  client/src/pages/manager/totalTransactions.tsx
  client/src/pages/manager/types.ts
  client/src/pages/user/components/accountOverview.tsx
  client/src/pages/user/components/transactionHistory.tsx
  client/src/pages/user/dashboard.tsx
  client/src/pages/user/onlineLoan.tsx
  client/src/pages/user/onlineTransfer.tsx
  client/src/pages/user/types.ts
  client/src/routes/navlinks.tsx
  pnpm-lock.yaml
Labels: frontend, database

#64 Finalize backend
  SQL/branchreports.sql
  SQL/customerViews.sql
  server/src/api/v1/api-doc.ts
  server/src/api/v1/handlers/account/checking/create.ts
  server/src/api/v1/handlers/account/checking/list.ts
  server/src/api/v1/handlers/account/deposit.ts
  server/src/api/v1/handlers/account/savings/create.ts
  server/src/api/v1/handlers/account/savings/list.ts
  server/src/api/v1/handlers/account/transfer.ts
  server/src/api/v1/handlers/account/transferHistory.ts
  server/src/api/v1/handlers/account/withdraw.ts
  server/src/api/v1/handlers/fixedDeposit/create.ts
  server/src/api/v1/handlers/fixedDeposit/list.ts
  server/src/api/v1/handlers/loan/installments.ts
  server/src/api/v1/handlers/report/branchWiseLateLoanInstallments.ts
  server/src/app.ts
Labels: backend
